name: structure_test
description: Test of project setup

publish_to: 'none'

version: 1.0.0+1
# Use comments below to track versions:
# DEV: 1.0.0+1
# STAGE: 1.0.0+1
# PROD: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.4.6
  firebase_analytics: ^10.7.2
  intl: ^0.18.1
  go_router: ^12.1.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600