// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class FirebaseOptionsSTAGE {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-bvJbCB8KSXIBfxgeyUoC_eqvRXVaKVI',
    appId: '1:246592880290:web:a5dd9345341572126721fb',
    messagingSenderId: '246592880290',
    projectId: 'structure-test-29057',
    authDomain: 'structure-test-29057.firebaseapp.com',
    storageBucket: 'structure-test-29057.appspot.com',
    measurementId: 'G-P053E3L43F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDazLz-Y9U8cbvTch5RcK5UyVpuxkRvFOM',
    appId: '1:246592880290:android:077d983a8791656c6721fb',
    messagingSenderId: '246592880290',
    projectId: 'structure-test-29057',
    storageBucket: 'structure-test-29057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADl2Cj-C7UH93hneki8jK7ZXUdp5NvVlw',
    appId: '1:246592880290:ios:a2cedd416496c10e6721fb',
    messagingSenderId: '246592880290',
    projectId: 'structure-test-29057',
    storageBucket: 'structure-test-29057.appspot.com',
    iosBundleId: 'com.appub.structure.structureTest.stage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADl2Cj-C7UH93hneki8jK7ZXUdp5NvVlw',
    appId: '1:246592880290:ios:799feaceb4beeae96721fb',
    messagingSenderId: '246592880290',
    projectId: 'structure-test-29057',
    storageBucket: 'structure-test-29057.appspot.com',
    iosBundleId: 'com.appub.structure.structureTest.RunnerTests',
  );
}
